default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # ローカルでは.envがあればそれを使う、なければ直接指定も可
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: secondpath_backend_test

production:
  <<: *default
  # DATABASE_URLから接続情報を読み込む
  url: <%= ENV["DATABASE_URL"] %>
  # Supabase (Transaction Mode) のための必須設定
  prepared_statements: false
  # SSL接続を強制
  sslmode: 'require'